# Generated by Django 4.2.30 on 2026-06-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=1000)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.TextField(blank=True)),
                ('claims', models.JSONField(blank=True, default=list)),
                ('framing_note', models.TextField(blank=True)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True)),
                ('fulltext_source', models.CharField(blank=True, max_length=16)),
                ('fulltext_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='feeds.feed')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='feeds.source')),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
                'indexes': [models.Index(fields=['is_read'], name='articles_ar_is_read_a00dfe_idx'), models.Index(fields=['is_saved'], name='articles_ar_is_save_2ba8d8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('feed', 'guid'), name='uniq_feed_guid'),
        ),
    ]
