# Generated by Django 4.2.30 on 2026-06-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summarized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tldr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='translated_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='translated_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='translation_lang',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
