# Generated by Django 4.2.30 on 2026-06-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_summarized_at_article_tldr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='enclosure_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='article',
            name='enclosure_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
