# Generated by Django 4.2.30 on 2026-06-25 15:46

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding_vec',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=256, null=True),
        ),
    ]
