# Generated by Django 4.2.30 on 2026-06-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_transcribe_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chapters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='play_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='play_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
