# Generated by Django 4.2.30 on 2026-06-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'is_read'], name='articles_ar_feed_id_0da4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'is_saved'], name='articles_ar_feed_id_cb19f6_idx'),
        ),
    ]
