# Generated by Django 4.2.30 on 2026-06-26 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0009_article_chapters_article_duration_article_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='queueitem',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='uniq_user_queue_article'),
        ),
    ]
