# Generated by Django 4.2.30 on 2026-06-26 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syncapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpodderDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(default='mobile', max_length=32)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpodder_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='gpodderdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='uniq_user_gpodder_device'),
        ),
    ]
