# Generated by Django 4.2.30 on 2026-06-16 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=500)),
                ('centroid', models.JSONField(blank=True, null=True)),
                ('neutral_summary', models.TextField(blank=True)),
                ('perspectives', models.JSONField(blank=True, default=dict)),
                ('bias_distribution', models.JSONField(blank=True, default=dict)),
                ('is_blindspot', models.BooleanField(default=False)),
                ('blindspot_side', models.CharField(blank=True, max_length=8)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('dirty', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='StoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(default=0.0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='articles.article')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_articles', to='stories.story')),
            ],
        ),
        migrations.AddConstraint(
            model_name='storyarticle',
            constraint=models.UniqueConstraint(fields=('story', 'article'), name='uniq_story_article'),
        ),
    ]
