# Generated by Django 4.2.30 on 2026-06-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='blindspot_notified',
            field=models.BooleanField(default=False),
        ),
    ]
