# Generated by Django 4.2.30 on 2026-06-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='synthesis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='synthesized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
