# Generated by Django 4.2.30 on 2026-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_synthesis_story_synthesized_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='location_country',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
