# Generated by Django 4.2.30 on 2026-06-25 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0006_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0007_article_embedding_vec_hnsw'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='En lenguaje natural: qué noticias quieres')),
                ('enabled', models.BooleanField(default=True)),
                ('min_score', models.PositiveSmallIntegerField(default=6)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feed', to='feeds.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('snippet', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('relevant', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='aifeeds.aifeed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('snippet', models.TextField(blank=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Descartada')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='aifeeds.aifeed')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.article')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='aifeedcandidate',
            constraint=models.UniqueConstraint(fields=('ai_feed', 'url'), name='uniq_aifeed_candidate_url'),
        ),
    ]
