# Generated by Django 4.2.30 on 2026-06-16 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('bias', models.CharField(choices=[('left', 'Izquierda'), ('lean_left', 'Centro-izquierda'), ('center', 'Centro'), ('lean_right', 'Centro-derecha'), ('right', 'Derecha'), ('unknown', 'Desconocido')], default='unknown', max_length=16)),
                ('factuality', models.CharField(blank=True, max_length=64)),
                ('bias_source', models.CharField(blank=True, choices=[('llm', 'LLM'), ('manual', 'Manual')], max_length=8)),
                ('bias_reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeds', to='feeds.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddConstraint(
            model_name='feed',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='uniq_user_feed_url'),
        ),
    ]
