# Generated by Django 4.2.30 on 2026-06-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_category_feed_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='auto_interval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='fetch_interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
