# Generated by Django 4.2.30 on 2026-06-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_feed_auto_interval_feed_fetch_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='crawler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='favicon',
            field=models.TextField(blank=True),
        ),
    ]
