# Generated by Django 4.2.30 on 2026-06-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_feed_crawler_source_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='etag',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='feed',
            name='fail_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='last_modified',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
