# Generated by Django 4.2.30 on 2026-06-17 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_tag_article_tags_tag_uniq_user_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0005_feed_etag_feed_fail_count_feed_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('pattern', models.CharField(blank=True, help_text='Regex (opcional)', max_length=300)),
                ('match_in', models.CharField(choices=[('any', 'Título o resumen'), ('title', 'Título'), ('summary', 'Resumen')], default='any', max_length=8)),
                ('action_mark_read', models.BooleanField(default=False)),
                ('action_star', models.BooleanField(default=False)),
                ('action_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.tag')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.category')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
