# Generated by Django 4.2.30 on 2026-06-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='kind',
            field=models.CharField(choices=[('rss', 'RSS'), ('podcast', 'Podcast'), ('youtube', 'YouTube')], default='rss', max_length=16),
        ),
    ]
