# Generated by Django 4.2.30 on 2026-06-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_feed_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='feed',
            name='playback_speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='feed',
            name='skip_intro',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='skip_outro',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
