# Generated by Django 4.2.30 on 2026-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_feed_description_feed_image_url_feed_playback_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='source',
            name='ownership',
            field=models.CharField(blank=True, choices=[('independent', 'Independiente'), ('state', 'Estatal'), ('partisan', 'Partidista'), ('unknown', 'Desconocido')], default='unknown', max_length=16),
        ),
    ]
