# Generated by Django 4.2.30 on 2026-06-17 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntitlements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(default='free', max_length=20)),
                ('beta_access', models.BooleanField(default=False, help_text='Acceso a funciones beta')),
                ('grants', models.JSONField(blank=True, default=list, help_text='Keys concedidas pese al tier')),
                ('denies', models.JSONField(blank=True, default=list, help_text='Keys denegadas explícitamente')),
                ('tier_expires', models.DateTimeField(blank=True, help_text='Al expirar, baja a free', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
